GET ${process.env.REACT_APP_SERVERURL}/api/trips
###
POST https://localhost:8800/api/trips/
Content-Type: application/json
{
    "tripName": "new Trip2",
    "tripDestination": "new destination2",
    "cost": 5000
}

###
